import { activity } from "./activity.interface";

export const data: activity[] = [
    {
        "id": 261127603,
        "courseId": 43101,
        "courseType": "Lesson",
        "courseTitle": "You Got a New Job! | Part 3 | Language in Context",
        "courseDesc": "Put everything together.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682880865109,
        "dateCompleted": 1682881113822,
        "sourceId": null,
        "mediaData": "81/3503",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261129802,
        "courseId": 43102,
        "courseType": "Lesson",
        "courseTitle": "She Said That... | Part 1 | Vocabulary",
        "courseDesc": "Learn how to talk about things that a person said.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682881808764,
        "dateCompleted": 1682882218423,
        "sourceId": null,
        "mediaData": "81/3504",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261130883,
        "courseId": 43103,
        "courseType": "Lesson",
        "courseTitle": "She Said That... | Part 2 | Grammar",
        "courseDesc": "Continue learning how to talk about things that a person said.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682882222453,
        "dateCompleted": 1682882754263,
        "sourceId": null,
        "mediaData": "81/3505",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261132128,
        "courseId": 43104,
        "courseType": "Lesson",
        "courseTitle": "She Said That... | Part 3 | Language in Context",
        "courseDesc": "Put everything together.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682882759765,
        "dateCompleted": 1682883188820,
        "sourceId": null,
        "mediaData": "81/3506",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261133108,
        "courseId": 43105,
        "courseType": "Lesson",
        "courseTitle": "She Got a New Job? | Part 1 | Vocabulary",
        "courseDesc": "Learn how to ask questions about what a person said.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682883194688,
        "dateCompleted": 1682883392551,
        "sourceId": null,
        "mediaData": "81/3507",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261133670,
        "courseId": 43106,
        "courseType": "Lesson",
        "courseTitle": "She Got a New Job? | Part 2 | Grammar",
        "courseDesc": "Continue learning how to ask questions about what a person said.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682883397908,
        "dateCompleted": 1682884096882,
        "sourceId": null,
        "mediaData": "81/3508",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261135918,
        "courseId": 43107,
        "courseType": "Lesson",
        "courseTitle": "She Got a New Job? | Part 3 | Language in Context",
        "courseDesc": "Put everything together.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682884204882,
        "dateCompleted": 1682884616035,
        "sourceId": null,
        "mediaData": "81/3509",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261137592,
        "courseId": 43108,
        "courseType": "Lesson",
        "courseTitle": "Unit 5 Review",
        "courseDesc": "Let’s review everything you learned in this unit.",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682884866588,
        "dateCompleted": 1682885658528,
        "sourceId": null,
        "mediaData": "81/5892",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261221076,
        "courseId": 43109,
        "courseType": "Unit Assessment",
        "courseTitle": "Unit 5 Quiz",
        "courseDesc": "This is the Unit Quiz. Good luck!",
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682912554150,
        "dateCompleted": 1682913015856,
        "sourceId": null,
        "mediaData": "81/5786",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": null,
        "status": null,
        "transcript": null
    },
    {
        "id": 261223257,
        "courseId": 52971,
        "courseType": "News",
        "courseTitle": "April 28, 2023",
        "courseDesc": null,
        "teacherDisplayName": null,
        "assessmentResult": null,
        "dateStarted": 1682913075232,
        "dateCompleted": 1682913340232,
        "sourceId": null,
        "mediaData": "1200",
        "noteId": null,
        "liveClassRecordingLink": null,
        "url": "https://lp2-player.openenglish.com/dailynews.html?q=eyJkYXRlIjoiMjAyMy0wNC0yOCIsImxldmVsIjoiSW50In0",
        "status": null,
        "transcript": null
    }
]